name: Buildbase

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/buildbase.yml"
      - "buildbase/*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [24.08]
    steps:
      - 
        name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: true
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - 
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Build base
        uses: hieupth/docker-action@v1
        with: 
          shell: bash
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
          image: nvcr.io/nvidia/tensorrt:${{matrix.version}}-py3
          options: |
            -v ./buildbase.sh:/build.sh
            -e TRITON_VERSION=${{matrix.version}}
          run: bash /build.sh
      -
        name: Push image
        run: |
          docker tag tritonserver ${{secrets.DOCKERHUB_USERNAME}}/tritonserverbuild:${{matrix.version}}
          docker push ${{secrets.DOCKERHUB_USERNAME}}/tritonserverbuild:${{matrix.version}}
