name: Build Runtime

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Buildbase]
    types: [completed]
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/buildruntime.yml"
      - "dockerfile"
      - "scripts/*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [24.08]
        variant: [base, trtllm, vllm]
        include:
          - variant: base
            base_image: hieupth/tritonserverbuild
            base_suffix: 
            image_tag:
          - variant: trtllm
            base_image: nvcr.io/nvidia/tritonserver
            base_suffix: -trtllm-python-py3
            image_tag: -trtllm
          - variant: vllm
            base_image: nvcr.io/nvidia/tritonserver
            base_suffix: -vllm-python-py3
            image_tag: -vllm
    steps:
      - 
        name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: true
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Build devel
        uses: docker/build-push-action@v5
        with:
          push: true
          file: dockerfile
          platforms: linux/amd64
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tritonserver:${{matrix.version}}${{matrix.image_tag}}
          build-args: |
            BASE=${{matrix.base_image}}:${{matrix.version}}${{matrix.base_suffix}}